Blocks:
  dragonStone:
    blockName: "DragonStone"
    regenTime: 10
    hardnessMultiplier: 500
    modelData: 0
    hasParticle: true
    hasEffect: true
    hasSound: true
    effects:
      particles:
        type: "DRAGON_BREATH"
        amount: 3
      effect:
        type: "DRAGON_BREATH"
        data: 1
        radius: 10
      sound:
        type: "ENTITY_IRON_GOLEM_DAMAGE"
        pitch: 10
        volume: 10
    drops:
      diamond:
        material: "DIAMOND"
        name: "&cDragonStoneDiamond"
        glowing: true
        data: 0
        lore:
          - "&aThis is a dragon stone diamond."
      ruby:
        material: "REDSTONE_BLOCK"
        name: "&cDragonStoneRuby"
        glowing: false
        data: 0
        lore:
          - "&aThis is a dragon stone ruby"

Messages:
  regionCommandUsage: "&c<region> <block>"
  regionRegisteredCommand: "&bRegion registered"
  blockNotFound: "&cThat block name doesn't seem to be correct, try again!"
  worldGuardRegionNotFound: "&cWorldGuard region with this name doesn't seem to exist, try again!"